### ISSUE TITLE
Kitchen Test fails during verify with undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by bbaugher** [someara/kitchen-dokken#62] opened 2017-01-27 21:28 UTC
[Here](https://gist.github.com/bbaugher/071ea1fdb8784650760ce56e054ae964) is my kitchen log. Seems like it might be failing [here](https://github.com/someara/kitchen-dokken/blob/master/lib/kitchen/transport/dokken.rb#L79)?

I managed to switch back to 1.1.0 to get around this

**Comment by tas50** [comment] 2017-02-07 10:21
We're seeing this in chef/chef tests @someara. We've pinned chef/chef and dk back to 1.1 for now to get around it.  Here's a failure in Travis: https://travis-ci.org/chef/chef/jobs/199125788

**Comment by someara** [comment] 2017-02-08 04:01
I've added tests to make sure that the code paths that connect over a tcp socket get exercised.

https://github.com/someara/kitchen-dokken/blob/d6d1d0026b9da63cc54b8dd87e427fd409562052/test/cookbooks/dokken_test/recipes/default.rb

I was expecting (hoping?) to reproduce this there, but no such luck.

Any more clues?

-s

**Comment by majormoses** [comment] 2017-02-11 00:43
seeing this as well.

**Comment by someara** [comment] 2017-02-11 00:47
can you post your .kitchen.dokken.yml?

**Comment by someara** [comment] 2017-02-11 00:48
and are you using a local or remote docker host

**Comment by majormoses** [comment] 2017-02-11 00:55
https://gist.github.com/majormoses/cf303fef69f75fd25f7bc6e245c6a38e local docker host running in jenkins.

**Comment by someara** [comment] 2017-02-11 01:01
looks fine... kitchen log?

**Comment by majormoses** [comment] 2017-02-11 01:04
@someara I will have to get that to you Monday

**Comment by majormoses** [comment] 2017-02-13 17:20
https://gist.github.com/majormoses/956067d920c93bf5a24a4a520efab927

**Comment by dhoer** [comment] 2017-02-19 06:58
Same issue here:https://travis-ci.org/dhoer/chef-flywaydb/builds/203057052

**Comment by atheiman** [comment] 2017-02-21 02:53
running into this as well with the rundeck cookbook, you can see full debug kitchen output in travis here https://travis-ci.org/Webtrends/rundeck/jobs/203660470#L6945

**Comment by someara** [comment] 2017-02-21 07:30
Aha. was able to hit this by cloning the rundeck repo..

converge works.... it seems to blow up in verify.
I noticed you're using serverspec rather than Inspec....

@bbaugher @tas50 @majormoses @dhoer are you all using serverspec as well?

-s

**Comment by bbaugher** [comment] 2017-02-21 15:03
Yes I am using serverspec

**Comment by someara** [comment] 2017-02-21 15:10
Manually tested this fix 749e3a104cefee6f0db1896ae11191edc7d05c1e against rundeck. Hopefully it should fix everyone up.

Released as 2.1.0 to make pinning easier

-s

**Comment by someara** [comment] 2017-02-21 15:11
spoke too soon... that's busted.... investigating

**Comment by dhoer** [comment] 2017-02-21 15:37
@someara yes, using serverspec

**Comment by someara** [comment] 2017-02-21 16:45
okay... lets give kitchen-dokken-2.1.1 a whirl

**Comment by dhoer** [comment] 2017-02-21 18:55
It works! https://travis-ci.org/dhoer/chef-flywaydb 👍 

Thanks for taking a look at this.

**Comment by bbaugher** [comment] 2017-02-21 22:23
Yes this fixed it for me

**Comment by atheiman** [comment] 2017-02-22 04:07
this seems to have fixed the issue for me as well. thanks!

**Comment by someara** [comment] 2017-02-22 10:31
@tas50 you should be good to go as well. closing this.

**Closed by someara** 2017-02-22 10:31 UTC

**Comment by dhoer** [comment] 2017-02-22 16:04
@someara FYI, I don't know if this fix is causing this, but windows build is super slow and fails on unit tests because it stalls out.  Unit tests run for over 30 minutes, before stalling out.

https://ci.appveyor.com/project/dhoer/chef-flywaydb/build/master-77

But pinning dokken to 1.1.0, the build is faster and no stalling. 

https://ci.appveyor.com/project/dhoer/chef-flywaydb/build/master-83

Does anything pop into your head as to why this would be?

**Comment by someara** [comment] 2017-02-22 17:05
There's nothing that should be making it slower.... if anything it should be faster since it's using binding mounting instead of SCP file into the data container.

Perhaps it's a transient thing? That kinda thing happens on Travis all the time due to noisy neighbors on the VM hosts.

**Comment by dhoer** [comment] 2017-02-22 17:47
I tested it, and it seems having dokken v2.1.1 gem will cause the build to fail on windows.  It doesn't make sense to me why that would be.  The code change doesn't look like it would cause this.  Note that windows is 32 bit, could that be the reason?

**Comment by someara** [comment] 2017-02-22 20:10
Perhaps theres a bug with Docker on Windows?
It's bind mounting 3 things... chef, kitchen, and verifier directories.

Not seeing anything in the appveyor logs, and I don't have access to a windows machine
-s

**Comment by dhoer** [comment] 2017-02-22 23:13
I'm not using docker on windows, it is just pulling in the kitchen-dokken. Not sure if it is kitchen-dokken or one of its dependencies causing the builds to stall.  But the behavior is repeatable and consistent when switching from 1.1.0 to 2.1.1.  I could maybe add a linux gem group, but I rather not, because it would mean updating 50+ chef cookbooks.

**Comment by someara** [comment] 2017-02-23 00:58
Its only deps are docker-api and test-kitchen.
I just pushed 2.1.2, which raises the test-kitchen dep to ~> 1.15.

Try that one out?

**Comment by dhoer** [comment] 2017-02-23 20:55
I will try to look at it this weekend.
